bool isGameStarted();
bool isCorrectAnswer();
bool isAboutToStart();
bool isSleeping();
bool isGameOver();
bool isWaitingForStart();
int getScore();
bool isLedActive(int index);
void startGame();
int getExtractedNumber();
void updateDifficult(int value);
int getTimer();
int getCurrentDifficult();
void pressButton(int index);
bool move();
void resume();
void setSleep();
int getLedNumber();